import { ArrowRight, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { AppShell } from "@/components/shared/app-shell";
import { Button } from "@/components/shared/action-button";

export function Interview() {
  const [, setLocation] = useLocation();
  const [answer, setAnswer] = useState("");
  const [recording, setRecording] = useState(false);
  return <AppShell><div className="interview-shell"><div className="interview-top"><Link href="/training/oops" className="back-link" data-testid="link-exit-interview">Exit interview</Link><span className="live-interview"><span className="live-dot" /> AI INTERVIEW / OOP</span><span>12 min</span></div><div className="interview-layout"><div className="interview-main"><div className="interviewer-avatar"><Sparkles size={25} /></div><div className="interviewer-label">PREPMASTER INTERVIEWER <span>Question 01 / 04</span></div><h1>Tell me about a time you chose composition over inheritance. What changed because of that choice?</h1><p className="interview-prompt">Take a breath. A clear, specific story beats a perfect one.</p><div className="answer-box"><textarea value={answer} onChange={(e) => setAnswer(e.target.value)} placeholder="Type your answer, or use the voice prompt to practice out loud…" data-testid="input-interview-answer" /><div className="answer-box-foot"><span>{answer.length} / 1200</span><button type="button" className={`record-button ${recording ? "recording" : ""}`} onClick={() => setRecording(!recording)} data-testid="button-record-answer"><span />{recording ? "Recording…" : "Practice out loud"}</button></div></div><div className="interview-actions"><span><ShieldCheck size={14} /> Private practice · no judgment</span><Button onClick={() => setLocation("/results/result-oops-interview")} disabled={!answer} icon={ArrowRight}>Submit answer</Button></div></div><aside className="interview-aside"><div className="interview-progress-head"><span>SESSION PROGRESS</span><strong>01 <small>/ 04</small></strong></div><div className="interview-steps"><div className="active"><span>01</span><div><strong>Design decision</strong><small>In progress</small></div></div><div><span>02</span><div><strong>Technical depth</strong><small>Up next</small></div></div><div><span>03</span><div><strong>Follow-up</strong><small>Locked</small></div></div><div><span>04</span><div><strong>Your debrief</strong><small>Locked</small></div></div></div><div className="interview-tip"><Sparkles size={16} /><p>Try the shape: context → decision → trade-off → result.</p></div></aside></div></div></AppShell>;
}
