import { CheckCircle2, FileText, MoreHorizontal, Search, Upload } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/shared/app-shell";
import { PageHeading } from "@/components/shared/page-heading";
import { Button } from "@/components/shared/action-button";
import { mockService, resourcesSeed } from "@/data/mock-data";

export function Resources() {
  const [resources, setResources] = useState(resourcesSeed);
  const [search, setSearch] = useState("");
  const shown = resources.filter((resource) => resource.name.toLowerCase().includes(search.toLowerCase()));
  const addDemo = () => { const next = { id: `r${resources.length + 1}`, name: "new interview notes.txt", type: "TXT", size: "12 KB", status: "Processing" as const }; setResources((current) => [...current, next]); void mockService.processResource().then(() => setResources((current) => current.map((item) => item.id === next.id ? { ...item, status: "Ready" } : item))); };
  return <AppShell><PageHeading eyebrow="Your library" title="My resources." description="The material behind your study map. Keep it close, keep it useful." action={<Button href="/resources/upload" icon={Upload}>Add resource</Button>} /><div className="resource-overview"><div><strong>{resources.length}</strong><span>resources in your library</span></div><div><strong>43</strong><span>topics extracted</span></div><div><strong>86%</strong><span>coverage of your target role</span></div><div className="resource-search"><Search size={16} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search your library" data-testid="input-search-resources" /></div></div><div className="resource-table"><div className="resource-table-head"><span>Resource</span><span>Type</span><span>Size</span><span>Status</span><span /></div>{shown.map((resource) => <div className="resource-row" key={resource.id} data-testid={`row-resource-${resource.id}`}><span className="resource-name"><span className="file-icon"><FileText size={17} /></span><strong>{resource.name}</strong></span><span className="mono-label">{resource.type}</span><span className="muted">{resource.size}</span><span className={`resource-status ${resource.status === "Ready" ? "ready" : "processing"}`}>{resource.status === "Ready" ? <CheckCircle2 size={14} /> : <span className="tiny-loader" />} {resource.status}</span><button className="icon-button" onClick={() => setResources((current) => current.filter((item) => item.id !== resource.id))} data-testid={`button-delete-resource-${resource.id}`}><MoreHorizontal size={17} /></button></div>)}{shown.length === 0 && <div className="empty-state"><Search size={20} /><strong>No resources match that search.</strong><p>Try a different name or add something new.</p></div>}</div><div className="dropzone" onClick={addDemo} role="button" tabIndex={0} data-testid="button-add-demo-resource"><Upload size={20} /><strong>Drop a file here or browse your library</strong><small>PDF, DOCX, TXT, or a course URL · up to 25 MB</small></div></AppShell>;
}
