import { ArrowRight, Check, Clock3, Lock, MessageSquare, Play } from "lucide-react";
import { Link, useParams } from "wouter";
import { AppShell } from "@/components/shared/app-shell";
import { topics } from "@/data/mock-data";

export function TrainingDetail() {
  const { trainingId } = useParams<{ trainingId: string }>();
  const topic = topics.find((item) => item.id === trainingId) || topics[0];
  return <AppShell><Link href="/training" className="back-link" data-testid="link-back-training">← Training</Link><div className="training-detail-head"><div><div className="eyebrow">Focused path / 12 minute session</div><h1>{topic.name}</h1><p>Work through each layer in order. Passing a rep unlocks the next one.</p></div><span className="session-count"><Clock3 size={16} /> 3 reps to ready</span></div><div className="session-grid"><Link href={`/assessment/assess-${topic.id}-basic`} className="session-card complete" data-testid="card-session-basic"><span className="session-number">01</span><div className="session-icon"><Check size={19} /></div><div><h2>Basic assessment</h2><p>Check the fundamentals and build a quick win.</p><small>8 questions · 10 min · completed 92%</small></div><ArrowRight size={18} /></Link><Link href={`/assessment/assess-${topic.id}-intermediate`} className="session-card current" data-testid="card-session-intermediate"><span className="session-number">02</span><div className="session-icon"><Play size={18} fill="currentColor" /></div><div><h2>Intermediate assessment</h2><p>Explain your choices and handle the follow-up.</p><small>8 questions · 12 min · your next rep</small></div><ArrowRight size={18} /></Link><Link href={`/assessment/assess-${topic.id}-advanced`} className="session-card locked" data-testid="card-session-advanced"><span className="session-number">03</span><div className="session-icon"><Lock size={17} /></div><div><h2>Advanced assessment</h2><p>Navigate ambiguity with trade-offs and precision.</p><small>Unlock after intermediate</small></div><ArrowRight size={18} /></Link><Link href={`/interview/interview-${topic.id}`} className="session-card interview-card" data-testid="card-session-interview"><span className="session-number">04</span><div className="session-icon"><MessageSquare size={18} /></div><div><h2>AI interview</h2><p>Say it out loud. Get feedback you can use.</p><small>Unlock after advanced</small></div><ArrowRight size={18} /></Link></div></AppShell>;
}
