import { ArrowRight, Check, FileText, Library, Sparkles, Upload } from "lucide-react";
import { type FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";
import { AppShell } from "@/components/shared/app-shell";

export function UploadPage() {
  const [, setLocation] = useLocation();
  const [tab, setTab] = useState<"file" | "url">("file");
  const [name, setName] = useState("");
  const [processing, setProcessing] = useState(false);
  const submit = (event: FormEvent) => { event.preventDefault(); setProcessing(true); window.setTimeout(() => setLocation("/resources"), 1300); };
  return <AppShell><Link href="/resources" className="back-link" data-testid="link-back-resources">← My resources</Link><div className="upload-layout"><div><div className="eyebrow">Add to your library</div><h1>Put your prep<br /><em>to work.</em></h1><p className="upload-lede">PrepMaster reads your material, finds the signal, and turns it into a focused training path.</p><div className="upload-steps"><span className="active"><b>01</b><small>Add material</small></span><span><b>02</b><small>We map topics</small></span><span><b>03</b><small>You build signal</small></span></div></div><form className="upload-panel" onSubmit={submit}><div className="segmented upload-tabs"><button type="button" className={tab === "file" ? "selected" : ""} onClick={() => setTab("file")} data-testid="button-upload-file"><Upload size={15} /> Upload file</button><button type="button" className={tab === "url" ? "selected" : ""} onClick={() => setTab("url")} data-testid="button-upload-url"><Library size={15} /> Paste URL</button></div>{tab === "file" ? <div className="file-picker"><div className="upload-symbol"><Upload size={25} /></div><strong>Choose a study file</strong><span>PDF, DOCX, TXT up to 25 MB</span><button type="button" className="button button-secondary" onClick={() => setName("system-design-notes.pdf")} data-testid="button-choose-file">Choose file</button>{name && <div className="chosen-file"><FileText size={15} /> {name} <Check size={15} /></div>}</div> : <label className="url-input">Course or article URL<input value={name} onChange={(e) => setName(e.target.value)} placeholder="https://..." required data-testid="input-resource-url" /></label>}<label>Give it a name<input value={tab === "file" ? name : ""} onChange={(e) => setName(e.target.value)} placeholder="e.g. Backend interview notes" data-testid="input-resource-name" /></label><div className="upload-note"><Sparkles size={16} /><span>We’ll extract topics and suggest your first training rep.</span></div><button className="button button-primary button-wide" disabled={processing || !name} data-testid="button-process-resource">{processing ? "Mapping your material…" : "Add and map resource"} <ArrowRight size={16} /></button></form></div></AppShell>;
}
